# Generated by Django 4.0.4 on 2022-05-07 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_anon_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_anon',
            name='author',
        ),
        migrations.CreateModel(
            name='AnonComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post_anon')),
            ],
        ),
    ]
