# Generated by Django 4.0.4 on 2022-04-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news',
            new_name='post_title',
        ),
    ]
