# Generated by Django 4.0.4 on 2022-04-27 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_comment_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='allpost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date published'),
        ),
    ]
