# Generated by Django 4.0.4 on 2022-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_comment_pub_date_alter_allpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='post_text',
            field=models.TextField(),
        ),
    ]
